### ISSUE TITLE
[BUG] Old name input system still in effect

### ISSUE THREAD

**Issue by Zuesue** [AIESydneyStudents/3SQUARED#54]
Scores from previous versions are maintained through versions. This means that you can have more than a 3 letter name due to the old name input system.
![GameOverMenu](https://user-images.githubusercontent.com/85092888/143957391-887f843a-3ba1-4881-b883-41abe12d70aa.PNG)

**Comment by Athied** [comment]
Not a real bug, old player names were still saved in your playerprefs before the 3 character cap system was added
