### ISSUE TITLE
[BUG] Yeti stuck on scoreboard

### ISSUE THREAD

**Issue by Zuesue** [AIESydneyStudents/3SQUARED#57]
As Yeti was moving around it tried to walk near the scoreboard, kept walking into the scoreboard and doing nothing else. Seemed like it couldn't do anything else.
![YetiStuck](https://user-images.githubusercontent.com/85092888/143959702-3836971c-7fba-462b-9697-762666fdb867.PNG)

**Comment by Athied** [comment]
Adjusted engage zone size so yeti will no longer try to walk into the scoreboard. Seems to be fixed.
