### ISSUE TITLE
[BUG] Penguins carrying the puck out of rink

### ISSUE THREAD

**Issue by Zuesue** [AIESydneyStudents/3SQUARED#58]
the velocity of the puck and penguin aligned so that the puck was being pushed by the penguin. When I tried to get between the puck and outside of rink, the penguin pushed it through me which lead to a game over.

**Comment by Athied** [comment]
Decided this wasn't a huge problem in terms of gameplay (partly player's fault) and although it is a bit unfair we simply don't have time to fix it
