### ISSUE TITLE
[BUG] Score flipboard has delay on initial score, but synced afterwards

### ISSUE THREAD

**Issue by DanielSohler** [AIESydneyStudents/3SQUARED#61]

**Comment by DanielSohler** [comment]
When the player hits the puck for the first time, the score board has a 0.5-1 second delay before updating both the text, and running the animation for the flipboard.

How its suppose to function, is that it should update the text and run the animation immediately when the puck collides with the player.

Steps to recreate:
Start game
Click 'Start'
Play game until puck collides with player

**Comment by Athied** [comment]
Extremely hard for us to notice delay, likely negligible to player
